// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoVpPDptsd7iaKaqwG2gUcTexfjqq42IE',
    appId: '1:599244212953:web:56ea2b01e911a0cd230cc8',
    messagingSenderId: '599244212953',
    projectId: 'fb-test-bds',
    authDomain: 'fb-test-bds.firebaseapp.com',
    storageBucket: 'fb-test-bds.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS-tf341gb7FVruJu12teGOL5irsJnyDU',
    appId: '1:599244212953:android:7892734480bd0010230cc8',
    messagingSenderId: '599244212953',
    projectId: 'fb-test-bds',
    storageBucket: 'fb-test-bds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYqM8x1q2fimPrRCKFKxT9efvCvhmJj3s',
    appId: '1:599244212953:ios:643fb0f2b28dce5d230cc8',
    messagingSenderId: '599244212953',
    projectId: 'fb-test-bds',
    storageBucket: 'fb-test-bds.firebasestorage.app',
    iosBundleId: 'com.example.flutterWorksheets',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYqM8x1q2fimPrRCKFKxT9efvCvhmJj3s',
    appId: '1:599244212953:ios:643fb0f2b28dce5d230cc8',
    messagingSenderId: '599244212953',
    projectId: 'fb-test-bds',
    storageBucket: 'fb-test-bds.firebasestorage.app',
    iosBundleId: 'com.example.flutterWorksheets',
  );
}
