Map<String, dynamic> mockingUser = {"id": "kfd98uz4odjf8844ß39jggj9043", "name": "Testuser", "is_authentificated": null};

Map<String, dynamic> mockingUserDatas = {
  "user_id": "kfd98uz4odjf8844ß39jggj9043", 
  "hold_1year": true,
  "currency": "eur",
  "favorites": [
    "bitcoin","ethereum","iota","bonk","doge","shiba-inu"], 
  "accounts": [
    {"name": "Bitcoin (EURO)", "coin_id": "bitcoin", "currency": "eur", "transactions": []},
    {"name": "Bitcoin (USD)", "coin_id": "bitcoin", "currency": "usd", "transactions": []},
    {"name": "Ethereum", "coind_id": "ethereum", "currency": "eur", "transactions": []}] 
};

List<dynamic> mockingCoins = [
  {"id": "bitcoin", "name": "Bitcoin", "symbol": "btc"}, 
  {"id": "ethereum", "name": "Ethereum", "symbol": "eth"}, 
  {"id": "ripple", "name": "XRP", "symbol": "xrp"}, 
  {"id": "tether", "name": "Tether", "symbol": "usdt"}, 
  {"id": "binancecoin", "name": "BNB", "symbol": "bnb"}, 
  {"id": "solana", "name": "Solana", "symbol": "sol"}, 
  {"id": "usd-coin", "name": "USDC", "symbol": "usdc"}, 
  {"id": "cardano", "name": "Cardano", "symbol": "ada"}, 
  {"id": "dogecoin", "name": "Dogecoin", "symbol": "doge"}, 
  {"id": "tron", "name": "TRON", "symbol": "trx"}, 
  {"id": "staked-ether", "name": "Lido Staked Ether", "symbol": "steth"}, 
  {"id": "wrapped-bitcoin", "name": "Wrapped Bitcoin", "symbol": "wbtc"}, 
  {"id": "chainlink", "name": "Chainlink", "symbol": "link"}, 
  {"id": "the-open-network", "name": "Toncoin", "symbol": "ton"}, 
  {"id": "avalanche-2", "name": "Avalanche", "symbol": "avax"}, 
  {"id": "wrapped-steth", "name": "Wrapped stETH", "symbol": "wsteth"}, 
  {"id": "leo-token", "name": "LEO Token", "symbol": "leo"}, 
  {"id": "stellar", "name": "Stellar", "symbol": "xlm"}, 
  {"id": "usds", "name": "USDS", "symbol": "usds"}, 
  {"id": "hedera-hashgraph", "name": "Hedera", "symbol": "hbar"}, 
  {"id": "shiba-inu", "name": "Shiba Inu", "symbol": "shib"}, 
  {"id": "sui", "name": "Sui", "symbol": "sui"}, 
  {"id": "polkadot", "name": "Polkadot", "symbol": "dot"}, 
  {"id": "litecoin", "name": "Litecoin", "symbol": "ltc"}, 
  {"id": "bitcoin-cash", "name": "Bitcoin Cash", "symbol": "bch"}, 
  {"id": "mantra-dao", "name": "MANTRA", "symbol": "om"}, 
  {"id": "pi-network", "name": "Pi Network", "symbol": "pi"}, 
  {"id": "bitget-token", "name": "Bitget Token", "symbol": "bgb"}, 
  {"id": "weth", "name": "WETH", "symbol": "weth"}, 
  {"id": "hyperliquid", "name": "Hyperliquid", "symbol": "hype"}, 
  {"id": "ethena-usde", "name": "Ethena USDe", "symbol": "usde"}, 
  {"id": "binance-bridged-usdt-bnb-smart-chain", "name": "Binance Bridged USDT (BNB Smart Chain)", "symbol": "bsc-usd"}, 
  {"id": "wrapped-eeth", "name": "Wrapped eETH", "symbol": "weeth"}, 
  {"id": "uniswap", "name": "Uniswap", "symbol": "uni"}, 
  {"id": "whitebit", "name": "WhiteBIT Coin", "symbol": "wbt"}, 
  {"id": "monero", "name": "Monero", "symbol": "xmr"}, 
  {"id": "aptos", "name": "Aptos", "symbol": "apt"}, 
  {"id": "near", "name": "NEAR Protocol", "symbol": "near"}, 
  {"id": "susds", "name": "sUSDS", "symbol": "susds"}, 
  {"id": "dai", "name": "Dai", "symbol": "dai"}, 
  {"id": "ethena-staked-usde", "name": "Ethena Staked USDe", "symbol": "susde"}, 
  {"id": "pepe", "name": "Pepe", "symbol": "pepe"}, 
  {"id": "okb", "name": "OKB", "symbol": "okb"}, 
  {"id": "internet-computer", "name": "Internet Computer", "symbol": "icp"}, 
  {"id": "gatechain-token", "name": "Gate", "symbol": "gt"}, 
  {"id": "aave", "name": "Aave", "symbol": "aave"}, 
  {"id": "mantle", "name": "Mantle", "symbol": "mnt"}, 
  {"id": "ondo-finance", "name": "Ondo", "symbol": "ondo"}, 
  {"id": "tokenize-xchange", "name": "Tokenize Xchange", "symbol": "tkx"}, 
  {"id": "ethereum-classic", "name": "Ethereum Classic", "symbol": "etc"}, 
  {"id": "coinbase-wrapped-btc", "name": "Coinbase Wrapped BTC", "symbol": "cbbtc"}, 
  {"id": "first-digital-usd", "name": "First Digital USD", "symbol": "fdusd"}, 
  {"id": "official-trump", "name": "Official Trump", "symbol": "trump"}, 
  {"id": "bittensor", "name": "Bittensor", "symbol": "tao"}, 
  {"id": "vechain", "name": "VeChain", "symbol": "vet"}, 
  {"id": "crypto-com-chain", "name": "Cronos", "symbol": "cro"}, 
  {"id": "cosmos", "name": "Cosmos Hub", "symbol": "atom"}, 
  {"id": "kaspa", "name": "Kaspa", "symbol": "kas"}, 
  {"id": "ethena", "name": "Ethena", "symbol": "ena"}, 
  {"id": "render-token", "name": "Render", "symbol": "render"}, 
  {"id": "filecoin", "name": "Filecoin", "symbol": "fil"}, 
  {"id": "celestia", "name": "Celestia", "symbol": "tia"}, 
  {"id": "sonic-3", "name": "Sonic (prev. FTM)", "symbol": "s"}, 
  {"id": "polygon-ecosystem-token", "name": "POL (ex-MATIC)", "symbol": "pol"}, 
  {"id": "lombard-staked-btc", "name": "Lombard Staked BTC", "symbol": "lbtc"}, 
  {"id": "arbitrum", "name": "Arbitrum", "symbol": "arb"}, 
  {"id": "fasttoken", "name": "Fasttoken", "symbol": "ftn"}, 
  {"id": "algorand", "name": "Algorand", "symbol": "algo"}, 
  {"id": "arbitrum-bridged-usdt-arbitrum", "name": "Arbitrum Bridged USDT (Arbitrum)", "symbol": "usdt"}, 
  {"id": "jupiter-exchange-solana", "name": "Jupiter", "symbol": "jup"}, 
  {"id": "story-2", "name": "Story", "symbol": "ip"}, 
  {"id": "blackrock-usd-institutional-digital-liquidity-fund", "name": "BlackRock USD Institutional Digital Liquidity Fund", "symbol": "buidl"}, 
  {"id": "optimism", "name": "Optimism", "symbol": "op"}, 
  {"id": "fetch-ai", "name": "Artificial Superintelligence Alliance", "symbol": "fet"}, 
  {"id": "kucoin-shares", "name": "KuCoin", "symbol": "kcs"}, 
  {"id": "solv-btc", "name": "Solv Protocol SolvBTC", "symbol": "solvbtc"}, 
  {"id": "binance-peg-weth", "name": "Binance-Peg WETH", "symbol": "weth"}, 
  {"id": "kelp-dao-restaked-eth", "name": "Kelp DAO Restaked ETH", "symbol": "rseth"}, 
  {"id": "nexo", "name": "NEXO", "symbol": "nexo"}, 
  {"id": "xdce-crowd-sale", "name": "XDC Network", "symbol": "xdc"}, 
  {"id": "quant-network", "name": "Quant", "symbol": "qnt"}, 
  {"id": "binance-staked-sol", "name": "Binance Staked SOL", "symbol": "bnsol"}, 
  {"id": "immutable-x", "name": "Immutable", "symbol": "imx"}, 
  {"id": "maker", "name": "Maker", "symbol": "mkr"}, 
  {"id": "movement", "name": "Movement", "symbol": "move"}, 
  {"id": "bonk", "name": "Bonk", "symbol": "bonk"}, 
  {"id": "worldcoin-wld", "name": "Worldcoin", "symbol": "wld"}, 
  {"id": "injective-protocol", "name": "Injective", "symbol": "inj"}, 
  {"id": "blockstack", "name": "Stacks", "symbol": "stx"}, 
  {"id": "rocket-pool-eth", "name": "Rocket Pool ETH", "symbol": "reth"}, 
  {"id": "dexe", "name": "DeXe", "symbol": "dexe"}, 
  {"id": "sei-network", "name": "Sei", "symbol": "sei"}, 
  {"id": "the-graph", "name": "The Graph", "symbol": "grt"}, 
  {"id": "theta-token", "name": "Theta Network", "symbol": "theta"}, 
  {"id": "lido-dao", "name": "Lido DAO", "symbol": "ldo"}, 
  {"id": "usual-usd", "name": "Usual USD", "symbol": "usd0"}, 
  {"id": "entangle", "name": "Entangle", "symbol": "ntgl"}, 
  {"id": "flare-networks", "name": "Flare", "symbol": "flr"}, 
  {"id": "eos", "name": "EOS", "symbol": "eos"}, 
  {"id": "paypal-usd", "name": "PayPal USD", "symbol": "pyusd"}];

List<dynamic> mockingCoinDatas = [
  {"id": "bitcoin", "current_price": 81641.0, "market_cap_rank" : 1}, 
  {"id": "ethereum", "current_price": 1932.05, "market_cap_rank" : 2}, 
  {"id": "ripple", "current_price": 2.29, "market_cap_rank" : 3}, 
  {"id": "tether", "current_price": 0.926344, "market_cap_rank" : 4}, 
  {"id": "binancecoin", "current_price": 581.3, "market_cap_rank" : 5}, 
  {"id": "solana", "current_price": 132.37, "market_cap_rank" : 6}, 
  {"id": "usd-coin", "current_price": 0.926284, "market_cap_rank" : 7}, 
  {"id": "dogecoin", "current_price": 0.169601, "market_cap_rank" : 8}, 
  {"id": "cardano", "current_price": 0.677, "market_cap_rank" : 9}, 
  {"id": "tron", "current_price": 0.212674, "market_cap_rank" : 10}, 
  {"id": "staked-ether", "current_price": 1926.68, "market_cap_rank" : 11}, 
  {"id": "wrapped-bitcoin", "current_price": 81490.0, "market_cap_rank" : 12}, 
  {"id": "chainlink", "current_price": 14.0, "market_cap_rank" : 13}, 
  {"id": "the-open-network", "current_price": 3.45, "market_cap_rank" : 14}, 
  {"id": "leo-token", "current_price": 9.04, "market_cap_rank" : 15}, 
  {"id": "wrapped-steth", "current_price": 2313.5, "market_cap_rank" : 16}, 
  {"id": "stellar", "current_price": 0.270102, "market_cap_rank" : 17}, 
  {"id": "avalanche-2", "current_price": 19.91, "market_cap_rank" : 18}, 
  {"id": "usds", "current_price": 0.926664, "market_cap_rank" : 19}, 
  {"id": "hedera-hashgraph", "current_price": 0.177917, "market_cap_rank" : 20}, 
  {"id": "shiba-inu", "current_price": 0.00001254, "market_cap_rank" : 21}, 
  {"id": "sui", "current_price": 2.24, "market_cap_rank" : 22}, 
  {"id": "polkadot", "current_price": 4.38, "market_cap_rank" : 23}, 
  {"id": "litecoin", "current_price": 87.03, "market_cap_rank" : 24}, 
  {"id": "mantra-dao", "current_price": 6.3, "market_cap_rank" : 25}, 
  {"id": "bitcoin-cash", "current_price": 307.18, "market_cap_rank" : 26}, 
  {"id": "pi-network", "current_price": 0.873415, "market_cap_rank" : 27}, 
  {"id": "weth", "current_price": 1931.59, "market_cap_rank" : 28}, 
  {"id": "bitget-token", "current_price": 4.5, "market_cap_rank" : 29}, 
  {"id": "hyperliquid", "current_price": 15.66, "market_cap_rank" : 30}, 
  {"id": "ethena-usde", "current_price": 0.925835, "market_cap_rank" : 31}, 
  {"id": "binance-bridged-usdt-bnb-smart-chain", "current_price": 0.926861, "market_cap_rank" : 32}, 
  {"id": "wrapped-eeth", "current_price": 2054.62, "market_cap_rank" : 33}, 
  {"id": "uniswap", "current_price": 6.5, "market_cap_rank" : 34}, 
  {"id": "whitebit", "current_price": 26.94, "market_cap_rank" : 35}, 
  {"id": "monero", "current_price": 203.52, "market_cap_rank" : 36}, 
  {"id": "near", "current_price": 2.75, "market_cap_rank" : 37}, 
  {"id": "aptos", "current_price": 5.43, "market_cap_rank" : 38}, 
  {"id": "susds", "current_price": 0.969527, "market_cap_rank" : 39}, 
  {"id": "pepe", "current_price": 0.00000729, "market_cap_rank" : 40}, 
  {"id": "dai", "current_price": 0.925963, "market_cap_rank" : 41}, 
  {"id": "ethena-staked-usde", "current_price": 1.075, "market_cap_rank" : 42}, 
  {"id": "okb", "current_price": 47.36, "market_cap_rank" : 43}, 
  {"id": "gatechain-token", "current_price": 21.96, "market_cap_rank" : 44}, 
  {"id": "aave", "current_price": 178.26, "market_cap_rank" : 45}, 
  {"id": "internet-computer", "current_price": 5.58, "market_cap_rank" : 46}, 
  {"id": "mantle", "current_price": 0.783452, "market_cap_rank" : 47}, 
  {"id": "ondo-finance", "current_price": 0.830441, "market_cap_rank" : 48}, 
  {"id": "tokenize-xchange", "current_price": 32.6, "market_cap_rank" : 49}, 
  {"id": "ethereum-classic", "current_price": 16.9, "market_cap_rank" : 50}, 
  {"id": "coinbase-wrapped-btc", "current_price": 81620.0, "market_cap_rank" : 51}, 
  {"id": "first-digital-usd", "current_price": 0.92522, "market_cap_rank" : 52}, 
  {"id": "official-trump", "current_price": 10.92, "market_cap_rank" : 53}, 
  {"id": "bittensor", "current_price": 250.81, "market_cap_rank" : 54}, 
  {"id": "vechain", "current_price": 0.02455319, "market_cap_rank" : 55}, 
  {"id": "crypto-com-chain", "current_price": 0.076116, "market_cap_rank" : 56}, 
  {"id": "cosmos", "current_price": 4.57, "market_cap_rank" : 57}, 
  {"id": "ethena", "current_price": 0.368355, "market_cap_rank" : 58}, 
  {"id": "kaspa", "current_price": 0.074056, "market_cap_rank" : 59}, 
  {"id": "filecoin", "current_price": 2.9, "market_cap_rank" : 60}, 
  {"id": "render-token", "current_price": 3.55, "market_cap_rank" : 61}, 
  {"id": "celestia", "current_price": 3.41, "market_cap_rank" : 62}, 
  {"id": "polygon-ecosystem-token", "current_price": 0.203467, "market_cap_rank" : 63}, 
  {"id": "sonic-3", "current_price": 0.552761, "market_cap_rank" : 64}, 
  {"id": "lombard-staked-btc", "current_price": 81279.0, "market_cap_rank" : 65}, 
  {"id": "arbitrum", "current_price": 0.361165, "market_cap_rank" : 66}, 
  {"id": "algorand", "current_price": 0.189999, "market_cap_rank" : 67}, 
  {"id": "fasttoken", "current_price": 3.73, "market_cap_rank" : 68}, 
  {"id": "jupiter-exchange-solana", "current_price": 0.529031, "market_cap_rank" : 69}, 
  {"id": "arbitrum-bridged-usdt-arbitrum", "current_price": 0.926363, "market_cap_rank" : 70}, 
  {"id": "blackrock-usd-institutional-digital-liquidity-fund", "current_price": 0.925727, "market_cap_rank" : 71}, 
  {"id": "optimism", "current_price": 0.835888, "market_cap_rank" : 72}, 
  {"id": "story-2", "current_price": 5.23, "market_cap_rank" : 73}, 
  {"id": "fetch-ai", "current_price": 0.504653, "market_cap_rank" : 74}, 
  {"id": "kucoin-shares", "current_price": 10.55, "market_cap_rank" : 75}, 
  {"id": "solv-btc", "current_price": 81426.0, "market_cap_rank" : 76}, 
  {"id": "binance-peg-weth", "current_price": 1932.88, "market_cap_rank" : 77}, 
  {"id": "kelp-dao-restaked-eth", "current_price": 2008.38, "market_cap_rank" : 78}, 
  {"id": "nexo", "current_price": 1.09, "market_cap_rank" : 79}, 
  {"id": "xdce-crowd-sale", "current_price": 0.068739, "market_cap_rank" : 80}, 
  {"id": "quant-network", "current_price": 73.13, "market_cap_rank" : 81}, 
  {"id": "bonk", "current_price": 0.00001342, "market_cap_rank" : 82}, 
  {"id": "binance-staked-sol", "current_price": 138.16, "market_cap_rank" : 83}, 
  {"id": "immutable-x", "current_price": 0.57417, "market_cap_rank" : 84}, 
  {"id": "worldcoin-wld", "current_price": 0.850437, "market_cap_rank" : 85}, 
  {"id": "maker", "current_price": 1176.94, "market_cap_rank" : 86}, 
  {"id": "movement", "current_price": 0.3991, "market_cap_rank" : 87}, 
  {"id": "blockstack", "current_price": 0.634403, "market_cap_rank" : 88}, 
  {"id": "injective-protocol", "current_price": 9.79, "market_cap_rank" : 89}, 
  {"id": "rocket-pool-eth", "current_price": 2182.35, "market_cap_rank" : 90}, 
  {"id": "dexe", "current_price": 16.13, "market_cap_rank" : 91}, 
  {"id": "sei-network", "current_price": 0.187786, "market_cap_rank" : 92}, 
  {"id": "theta-token", "current_price": 0.90345, "market_cap_rank" : 93}, 
  {"id": "the-graph", "current_price": 0.094326, "market_cap_rank" : 94}, 
  {"id": "lido-dao", "current_price": 1.0, "market_cap_rank" : 95}, 
  {"id": "usual-usd", "current_price": 0.924142, "market_cap_rank" : 96}, 
  {"id": "flare-networks", "current_price": 0.01358799, "market_cap_rank" : 97}, 
  {"id": "eos", "current_price": 0.529133, "market_cap_rank" : 98}, 
  {"id": "solv-protocol-solvbtc-bbn", "current_price": 80885.0, "market_cap_rank" : 99}, 
  {"id": "paypal-usd", "current_price": 0.926625, "market_cap_rank" : 100}];

List<dynamic> searchCoins = mockingCoins;